baseURL: 'https://timely-frangipane-57520c.netlify.app'
languageCode: en-us
title: Galeri Seismologi
disablePathToLower: false

themesDir: 'themes'
#theme = "Hugo-Octopress"
theme: PaperMod
googleAnalytics: UA-123-45
# Disqus shortcode
# Disable comments for any individual post by adding "comments: false" in its frontmatter
disqusShortname: galeri-seismologi

cover:
 image: 'https://i.ibb.co/K0HVPBd/paper-mod-profilemode.png'
 # can also paste direct link from external site
 # ex. https://i.ibb.co/K0HVPBd/paper-mod-profilemode.png
 alt: this is a post image
 caption: this is the image
 relative: false # To use relative path for cover image, used in hugo Page-bundles
# image: 'https://i.ibb.co/K0HVPBd/paper-mod-profilemode.png'
# alt: This is a post image
# caption: This is the image

# Number of blog posts in each pagination page
paginate: 6

permalinks:

# Configures post URLs
post: '/:slug/'

# Make tags and categories work
indexes:
    tag: 'tags'
    category: 'categories'

params:
 author: Me
 
 
 homeInfoParams:
  Title: 'Galeri Seismologi'
  Content: '*Halo semua, Selamat datang di **Galeri Seismologi**, sebuah media untuk saling berbagi dan berdiskusi seputar dunia seismologi. Bagi anda mahasiswa ilmu kebumian, akademisi, praktisi kegempaan atau siapapun yang cinta dengan bidang ini, mari bergabung dan belajar bersama. Catatan-catatan ini saya tulis sebagai sebuah dokumentasi proses belajar yang saya lakukan dan semoga dapat bermanfaat bagi kita semua*'
  
 socialIcons:
    - name: facebook
      url: "https://facebook.com/"
    - name: twitter
      url: "https://twitter.com/"
    - name: instagram
    - name: github
   # - name: whatsapp
 
 ShowbreadCrumbs: true
 
 ShowReadingTime: true
 
 ShowShareButtons: true
 
 ShowPostNavLinks: true
 
 ShowToc: true
 
 TocOpen: true
 
 ShowCodeCopyButtons: true
 
  
 fuseOpts:
  isCaseSensitive: false
  shouldSort: true
  location: 0
  distance: 1000
  threshold: 0.4
  minMatchCharLength: 0
  keys: ["title", "permalink", "summary", "content"]
 
 
 #comments: true
 cover:
  responsiveImages: false
  LinkFullImages: true

outputs:
 home:
  - HTML
  - RSS
  - JSON # is necessary

 #pygmentsUseClasses: true
markup:
 highlight:
  anchorLineNos: true
  codeFences: true
  guessSyntax: true
  lineNos: true
  style: ubntu




menu:
  main:
   - identifier: home
     name: Home
     url: '/'
     weight: 1
   - identifier: 'content'
     name: 'Content'
     url: '/content'
     weight: 2
   - identifier: 'categories'
     name: 'Categories'
     url: '/categories'
     weight: 3
   - identifier: 'tags'
     name: 'Tags'
     url: '/tags'
     weight: 4
   - identifier: 'galeries'
     name: 'Galeries'
     url: '/galeries'
     weight: 5
   - identifier: 'archives'
     name: 'Archives'
     url: '/archives'
     weight: 6
   - identifier: 'search'
     name: 'Search'
     url: '/search'
     weight: 7
   - identifier: 'about'
     name: 'About Us'
     url: '/about/'
     weight: 8
  